### ISSUE TITLE
error Class 'Laminas\Validator\AbstractValidator' not found

### ISSUE THREAD

**Issue by nadia-am** [laminas/laminas-captcha#16]
I install this package laminas cpatcha base on this instruction https://docs.laminas.dev/laminas-captcha/
but on usage https://docs.laminas.dev/laminas-captcha/usage/ get error Class 'Laminas\Validator\AbstractValidator' not found

**Comment by froschdesign** [comment]
The laminas-validator must be added to the "require" section of `composer.json`:

https://github.com/laminas/laminas-captcha/blob/6b0b98d388b713119cbb5788ea0b90cd6e63513a/composer.json#L42

Because all provided adapters are based on `Laminas\Captcha\AbstractAdapter`:

https://github.com/laminas/laminas-captcha/blob/6b0b98d388b713119cbb5788ea0b90cd6e63513a/src/AbstractAdapter.php#L20

@nadia-am 
Are you willing to create a pull request?
